### ISSUE TITLE
Examples are not good examples

### ISSUE THREAD

**Issue by niemeyer** [ubuntu-core/snappy-testdata#1]
These look like snapcraft examples, rather than snappy per se, and they seem somewhat out of date.

We should either fix them in the next couple of days, or just take the repository down until we have better content to show here.

**Comment by sergiusens** [comment]
These are not snapcraft examples, these are meant to be assembled only through `snappy build` (or the soon to be `snapcraft snap [dir]`)

**Comment by chipaca** [comment]
Each of these serves to demonstrate individual features of snappy itself, and are often used for testing those features. Which ones are out of date, and how?

**Comment by niemeyer** [comment]
A repository of examples for how to build snaps should be based on snapcraft, not snappy's internal format. That would be equivalent to having an exploded deb file as an example of debian packaging.

We can surely have testing content somewhere, but right now that's not what it looks like.

**Comment by chipaca** [comment]
I'm not sure snapcraft supports all these directly, or if it ever will. Also they operate at different levels.

I guess I'm just not seeing what your problem is with this.

**Comment by niemeyer** [comment]
Again, my problem with this is that I don't want people to navigate into the ubuntu-core project and find these as examples of how to build snaps. The way to build snaps is with snapcraft, not handcrafting the content of a snap by hand. I'm slightly surprised this is not obvious.

**Comment by chipaca** [comment]
Ah! Then just renaming the repo to "snappy-test-snaps" or something similar should be enough, right?

**Comment by niemeyer** [comment]
Alright, I renamed the repository to "snappy-testdata". Closing the issue.
